sonar.projectKey=nudam-git_8.2CDevSecOps
sonar.organization=nudam-git
sonar.host.url=https://sonarcloud.io
sonar.token=${SONAR_TOKEN}

sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,test/**,tests/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.projectName=8.2CDevSecOps
sonar.sourceEncoding=UTF-8
